import Experience1 from '../../assets/images/houseSample/room-1.jpg';
import Experience2 from '../../assets/images/houseSample/room-2.jpg';
import Experience3 from '../../assets/images/houseSample/room-3.jpg';
import Experience4 from '../../assets/images/houseSample/room-4.jpg';
import Experience5 from '../../assets/images/houseSample/room-5.jpg';
import Experience6 from '../../assets/images/houseSample/room-6.jpg';
import Experience7 from '../../assets/images/houseSample/room-7.jpg';
import Experience8 from '../../assets/images/houseSample/room-8.jpg';
import Experience9 from '../../assets/images/houseSample/room-9.jpg';
import Experience10 from '../../assets/images/houseSample/room-10.jpg';
import Experience11 from '../../assets/images/houseSample/room-11.jpg';
import Experience12 from '../../assets/images/houseSample/room-12.jpg';
import Experience13 from '../../assets/images/houseSample/ex1.jpg';

export const ExperiencesData = [
  {
    pk: 1,
    photo: Experience13,
    title: 'Discover Banff National Park Day',
    rating: '4.87(1000) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 2,
    photo: Experience2,
    title: 'Discover Banff National Park Day',
    rating: '4.87(987) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 3,
    photo: Experience3,
    title: 'Discover Banff National Park Day',
    rating: '4.87(555) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 4,
    photo: Experience4,
    title: 'Discover Banff National Park Day',
    rating: '4.87(444) · 11 hours · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 5,
    photo: Experience5,
    title: 'Discover Banff National Park Day',
    rating: '4.87(222) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 6,
    photo: Experience6,
    title: 'Discover Banff National Park Day',
    rating: '4.87(111) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 7,
    photo: Experience7,
    title: 'Discover Banff National Park Day',
    rating: '4.87(321) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 8,
    photo: Experience8,
    title: 'Discover Banff National Park Day',
    rating: '4.87(123) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 9,
    photo: Experience9,
    title: 'Discover Banff National Park Day',
    rating: '4.87(544) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 10,
    photo: Experience10,
    title: 'Discover Banff National Park Day',
    rating: '4.87(435) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 11,
    photo: Experience11,
    title: 'Discover Banff National Park Day',
    rating: '4.87(75) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 12,
    photo: Experience12,
    title: 'Discover Banff National Park Day',
    rating: '4.87(22) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 13,
    photo: Experience1,
    title: 'Discover Banff National Park Day',
    rating: '4.87(174) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 14,
    photo: Experience2,
    title: 'Discover Banff National Park Day',
    rating: '4.87(323) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 15,
    photo: Experience5,
    title: 'Discover Banff National Park Day',
    rating: '4.87(123) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 16,
    photo: Experience6,
    title: 'Discover Banff National Park Day',
    rating: '4.87(123) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 17,
    photo: Experience7,
    title: 'Discover Banff National Park Day',
    rating: '4.87(333) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 18,
    photo: Experience8,
    title: 'Discover Banff National Park Day',
    rating: '4.87(777) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 19,
    photo: Experience9,
    title: 'Discover Banff National Park Day',
    rating: '4.87(999) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 20,
    photo: Experience10,
    title: 'Discover Banff National Park Day',
    rating: '4.87(888) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 21,
    photo: Experience11,
    title: 'Discover Banff National Park Day',
    rating: '4.87(835) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 22,
    photo: Experience12,
    title: 'Discover Banff National Park Day',
    rating: '4.87(123) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
  {
    pk: 23,
    photo: Experience1,
    title: 'Discover Banff National Park Day',
    rating: '4.87(1000) · 11 hours',
    City: 'Calgary',
    Province: 'Alberta',
    Country: 'Canada',
    price: '562',
  },
];
